import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/themes";
import { Inter as FontSans } from "next/font/google";
import "@/assets/styles/global.css";
import { Navbar } from "@/components/layout/client/Navbar";
import { ScrollToTop } from "@/components/layout/client/ScrollToTop";

export const metadata: Metadata = {
  title: "AI Resume Matcher",
  description: "Generated by AI Resume Matcher",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute='class'
      defaultTheme='system'
      enableSystem
      disableTransitionOnChange
    >
      <Navbar />
      {children}
      <ScrollToTop />
    </ThemeProvider>
  );
}
