import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/assets/styles/admin.css";

// const inter = Inter({ subsets: ["latin"] });
const appName = process.env.APP_NAME || "ARM";

export const metadata: Metadata = {
  title: appName,
  description: "Generated by ARM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen min-w-[1200px] bg-background font-sans antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
