import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ThemeProvider } from "@/components/common/ThemeProvider";
// import { Inter } from "next/font/google";
import { AdminLayout } from "@/components/layout/AdminLayout";
import { cn } from "@/lib/utils";
import "@/assets/styles/admin.css";

// const inter = Inter({ subsets: ["latin"] });
const appName = process.env.APP_NAME || "ARM";

export const metadata: Metadata = {
  title: appName,
  description: "Generated by Henry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen min-w-[1200px] bg-background font-sans antialiased"
        )}
      >
        <ThemeProvider
          attribute='data-prefers-color'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >
          <AntdRegistry>
            <AdminLayout appName={appName}>{children}</AdminLayout>
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
